#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 2 "parser.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "symbolTable.c"
int i=1,k=-1,l=-1;
int j=0;
char curfunc[100];
int stack[100];
int top=0;
int plist[100],flist[100];
int end[100];
int arr[10];
int ct=0,c=0,b;
int loop = 0;
int errc=0;
int type=0;
extern int yylineno;

#line 30 "parser.y"
typedef union
{
	int ival;
	char *str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	VOID	260
#define	ID	261
#define	NUM	262
#define	REAL	263
#define	WHILE	264
#define	IF	265
#define	RETURN	266
#define	PREPROC	267
#define	LE	268
#define	STRING	269
#define	PRINT	270
#define	FUNCTION	271
#define	DO	272
#define	ARRAY	273
#define	ELSE	274
#define	STRUCT	275
#define	STRUCT_VAR	276
#define	FOR	277
#define	GE	278
#define	EQ	279
#define	NE	280
#define	INC	281
#define	DEC	282


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int VOID;
static const int ID;
static const int NUM;
static const int REAL;
static const int WHILE;
static const int IF;
static const int RETURN;
static const int PREPROC;
static const int LE;
static const int STRING;
static const int PRINT;
static const int FUNCTION;
static const int DO;
static const int ARRAY;
static const int ELSE;
static const int STRUCT;
static const int STRUCT_VAR;
static const int FOR;
static const int GE;
static const int EQ;
static const int NE;
static const int INC;
static const int DEC;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,VOID=260
	,ID=261
	,NUM=262
	,REAL=263
	,WHILE=264
	,IF=265
	,RETURN=266
	,PREPROC=267
	,LE=268
	,STRING=269
	,PRINT=270
	,FUNCTION=271
	,DO=272
	,ARRAY=273
	,ELSE=274
	,STRUCT=275
	,STRUCT_VAR=276
	,FOR=277
	,GE=278
	,EQ=279
	,NE=280
	,INC=281
	,DEC=282


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::FLOAT=259;
const int YY_parse_CLASS::VOID=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::NUM=262;
const int YY_parse_CLASS::REAL=263;
const int YY_parse_CLASS::WHILE=264;
const int YY_parse_CLASS::IF=265;
const int YY_parse_CLASS::RETURN=266;
const int YY_parse_CLASS::PREPROC=267;
const int YY_parse_CLASS::LE=268;
const int YY_parse_CLASS::STRING=269;
const int YY_parse_CLASS::PRINT=270;
const int YY_parse_CLASS::FUNCTION=271;
const int YY_parse_CLASS::DO=272;
const int YY_parse_CLASS::ARRAY=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::STRUCT=275;
const int YY_parse_CLASS::STRUCT_VAR=276;
const int YY_parse_CLASS::FOR=277;
const int YY_parse_CLASS::GE=278;
const int YY_parse_CLASS::EQ=279;
const int YY_parse_CLASS::NE=280;
const int YY_parse_CLASS::INC=281;
const int YY_parse_CLASS::DEC=282;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		181
#define	YYFLAG		-32768
#define	YYNTBASE	43

#define YYTRANSLATE(x) ((unsigned)(x) <= 282 ? yytranslate[x] : 68)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    29,
    30,    39,    37,    31,    38,     2,    40,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    34,    36,
    28,    35,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    41,     2,    42,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    32,     2,    33,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    10,    16,    23,    27,    29,    32,
    34,    36,    38,    42,    45,    47,    48,    50,    52,    54,
    56,    58,    62,    65,    69,    71,    77,    79,    87,    93,
   101,   102,   103,   117,   118,   119,   129,   133,   137,   141,
   145,   148,   151,   155,   159,   161,   165,   169,   173,   177,
   179,   181,   185,   189,   191,   195,   197,   204,   209,   211,
   215,   217,   219,   223,   229,   231,   235,   239,   243,   247,
   253,   259,   265,   271,   273,   275,   277,   283,   286,   290,
   297,   304,   309
};

static const short yyrhs[] = {    44,
    43,     0,    12,    43,     0,    67,    43,     0,     0,    47,
     6,    29,    30,    48,     0,    47,     6,    29,    45,    30,
    48,     0,    45,    31,    46,     0,    46,     0,    47,     6,
     0,     3,     0,     4,     0,     5,     0,    32,    49,    33,
     0,    49,    50,     0,    48,     0,     0,    67,     0,    52,
     0,    53,     0,    56,     0,    51,     0,    11,    66,    34,
     0,    11,    34,     0,    11,     6,    34,     0,    34,     0,
    15,    29,    14,    30,    34,     0,    48,     0,    17,    48,
     9,    29,    59,    30,    34,     0,    10,    29,    59,    30,
    48,     0,    10,    29,    59,    30,    48,    19,    48,     0,
     0,     0,    22,    29,    59,    34,    59,    34,    59,    30,
    32,    54,    49,    55,    33,     0,     0,     0,     9,    29,
    59,    30,    32,    57,    49,    58,    33,     0,    59,    13,
    59,     0,    59,    23,    59,     0,    59,    25,    59,     0,
    59,    24,    59,     0,    59,    26,     0,    59,    27,     0,
    59,    35,    59,     0,    59,    36,    59,     0,    61,     0,
     6,    28,    66,     0,     6,    37,    60,     0,     6,    31,
    60,     0,    66,    31,    60,     0,     6,     0,    66,     0,
     6,    28,    61,     0,     6,    31,    61,     0,    64,     0,
    66,    31,    61,     0,     6,     0,     6,    28,     6,    29,
    62,    30,     0,     6,    29,    62,    30,     0,    66,     0,
    62,    31,    63,     0,    63,     0,     6,     0,     6,    28,
    65,     0,     6,    28,    29,    65,    30,     0,     6,     0,
    65,    37,    65,     0,    65,    38,    65,     0,    65,    39,
    65,     0,    65,    40,    65,     0,    29,    65,    37,    65,
    30,     0,    29,    65,    38,    65,    30,     0,    29,    65,
    39,    65,    30,     0,    29,    65,    40,    65,    30,     0,
    66,     0,     7,     0,     8,     0,    47,     6,    28,    66,
    34,     0,    61,    34,     0,    47,     6,    34,     0,    47,
     6,    41,    60,    42,    34,     0,    20,     6,    32,    67,
    33,    34,     0,    20,     6,     6,    34,     0,     1,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    38,    39,    40,    41,    44,    58,    77,    78,    81,    84,
    85,    86,    89,    92,    93,    94,    97,    98,    99,   100,
   101,   102,   110,   111,   118,   119,   120,   123,   126,   127,
   130,   130,   131,   133,   133,   134,   136,   137,   138,   139,
   140,   141,   142,   143,   144,   147,   148,   149,   150,   151,
   152,   155,   171,   176,   177,   178,   183,   201,   225,   228,
   229,   232,   244,   245,   248,   263,   264,   265,   266,   267,
   268,   269,   270,   271,   274,   275,   278,   303,   316,   339,
   370,   373,   376
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"VOID","ID","NUM","REAL","WHILE","IF","RETURN","PREPROC","LE","STRING","PRINT",
"FUNCTION","DO","ARRAY","ELSE","STRUCT","STRUCT_VAR","FOR","GE","EQ","NE","INC",
"DEC","'='","'('","')'","','","'{'","'}'","';'","'>'","'<'","'+'","'-'","'*'",
"'/'","'['","']'","start","Function","parameter_list","parameter","Type","CompoundStmt",
"StmtList","stmt","dowhile","if","for","@1","@2","while","@3","@4","expr1","assignment",
"assignment1","paralist","param","assignment2","exp","consttype","Declaration",
""
};
#endif

static const short yyr1[] = {     0,
    43,    43,    43,    43,    44,    44,    45,    45,    46,    47,
    47,    47,    48,    49,    49,    49,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    51,    52,    52,
    54,    55,    53,    57,    58,    56,    59,    59,    59,    59,
    59,    59,    59,    59,    59,    60,    60,    60,    60,    60,
    60,    61,    61,    61,    61,    61,    61,    61,    61,    62,
    62,    63,    64,    64,    65,    65,    65,    65,    65,    65,
    65,    65,    65,    65,    66,    66,    67,    67,    67,    67,
    67,    67,    67
};

static const short yyr2[] = {     0,
     2,     2,     2,     0,     5,     6,     3,     1,     2,     1,
     1,     1,     3,     2,     1,     0,     1,     1,     1,     1,
     1,     3,     2,     3,     1,     5,     1,     7,     5,     7,
     0,     0,    13,     0,     0,     9,     3,     3,     3,     3,
     2,     2,     3,     3,     1,     3,     3,     3,     3,     1,
     1,     3,     3,     1,     3,     1,     6,     4,     1,     3,
     1,     1,     3,     5,     1,     3,     3,     3,     3,     5,
     5,     5,     5,     1,     1,     1,     5,     2,     3,     6,
     6,     4,     1
};

static const short yydefact[] = {     0,
    83,    10,    11,    12,    56,    75,    76,     0,     0,     0,
     0,     0,    54,    59,     0,     0,     0,     0,     2,     0,
     1,     0,    78,     0,     3,    56,     0,    52,    63,    59,
    62,     0,    61,    53,     0,     0,     0,     0,    79,     0,
    55,     0,    65,     0,     0,    74,     0,     0,     0,     0,
    58,     0,    82,     0,     0,     0,     0,     0,     8,     0,
    50,     0,    51,     0,     0,    64,     0,     0,     0,     0,
    66,    67,    68,    69,    60,     0,     0,    77,    16,     5,
     0,     0,     9,     0,     0,     0,     0,     0,    57,     0,
     0,     0,     0,    81,    15,     0,     6,     7,    46,    48,
    47,    80,    49,    70,    71,    72,    73,     0,     0,     0,
     0,     0,     0,    13,    25,    27,    14,    21,    18,    19,
    20,    17,     0,     0,     0,    23,     0,     0,     0,     0,
     0,    45,     0,    24,    22,     0,     0,     0,     0,     0,
     0,     0,    41,    42,     0,     0,     0,     0,     0,     0,
     0,    37,    38,    40,    39,    34,    43,    44,    29,    26,
     0,     0,    16,     0,     0,     0,     0,    30,    28,     0,
     0,     0,    36,    31,    16,     0,     0,    33,     0,     0,
     0
};

static const short yydefgoto[] = {    19,
    10,    58,    59,    11,    95,    96,   117,   118,   119,   120,
   175,   177,   121,   163,   171,   131,    62,   132,    32,    33,
    13,    29,    14,    15
};

static const short yypact[] = {   324,
-32768,-32768,-32768,-32768,    56,-32768,-32768,   324,    14,   324,
    16,     7,-32768,   -17,   324,    19,    28,   137,-32768,     3,
-32768,    84,-32768,   137,-32768,   309,    57,-32768,   221,   314,
-32768,    20,-32768,-32768,    37,   223,    50,     8,-32768,   152,
-32768,    28,-32768,    57,    68,-32768,    57,    57,    57,    57,
-32768,    28,-32768,    70,    55,    58,    62,    86,-32768,    91,
     9,    67,    93,   109,   251,-32768,    57,    57,    57,    57,
   221,   221,   221,   221,-32768,   -11,    65,-32768,    62,-32768,
    62,   189,-32768,    50,   152,   152,    95,   152,-32768,    98,
   132,   234,   264,-32768,-32768,   146,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   105,   119,    -1,
   135,    62,   136,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   137,   137,   139,-32768,   148,   182,   190,   137,
   212,-32768,   227,-32768,-32768,   168,   187,   242,   137,   137,
   137,   137,-32768,-32768,   186,   137,   137,    62,   185,   137,
   137,    43,    43,    43,    43,-32768,    43,    43,   202,-32768,
   257,   272,    62,    62,   207,   137,   180,-32768,-32768,   287,
   211,   191,-32768,-32768,    62,   200,   213,-32768,   245,   249,
-32768
};

static const short yypgoto[] = {    29,
-32768,-32768,   174,   -35,   -53,  -144,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   -20,    89,     0,   233,   253,
-32768,    33,     5,   -34
};


#define	YYLAST		354


static const short yytable[] = {    12,
    54,    55,    60,    80,   125,     6,     7,    12,    35,    12,
     2,     3,     4,    24,    12,    28,    37,    34,   167,    20,
    30,    22,    39,    41,    26,     6,     7,    97,   179,    40,
   176,    46,   126,    31,    36,    12,    84,    57,    21,    85,
    23,    56,   116,    25,    63,    86,    60,    27,    46,    51,
    52,    46,    46,    46,    46,   139,     6,     7,   129,    45,
    54,   122,    43,     6,     7,   140,   141,   142,   143,   144,
    53,    46,    46,    46,    46,    76,    65,   146,   147,    71,
    72,    73,    74,    16,    17,    44,    18,    77,    99,    63,
    63,    78,    63,    79,   159,    12,    83,    66,    94,    90,
    91,    92,    93,   133,    67,    68,    69,    70,    87,   138,
   168,    37,    38,   116,   127,    81,    82,    39,   152,   153,
   154,   155,   116,    88,    40,   157,   158,   104,   102,   161,
   162,    54,   122,   123,    47,    48,    49,    50,    89,    52,
    54,   122,     5,     6,     7,   170,     1,   124,     2,     3,
     4,     5,     6,     7,   108,   109,   110,    61,     6,     7,
   111,   105,   112,   128,   130,     9,    12,   113,    47,    48,
    49,    50,   134,   100,   101,    12,   103,    79,   114,   115,
     1,   135,     2,     3,     4,     5,     6,     7,   108,   109,
   110,     2,     3,     4,   111,   136,   112,   149,   137,     9,
     1,   113,     2,     3,     4,     5,     6,     7,   108,   109,
   110,    79,   -35,   115,   111,   150,   112,   156,   160,     9,
   164,   113,   174,     1,   139,     2,     3,     4,     5,     6,
     7,    79,   -32,   115,   140,   141,   142,   143,   144,   139,
   169,   145,     9,   173,   180,   178,   146,   147,   181,   140,
   141,   142,   143,   144,   139,    98,   148,    47,    48,    49,
    50,   146,   147,   106,   140,   141,   142,   143,   144,   139,
    47,    48,    49,    50,    64,   151,   146,   147,     0,   140,
   141,   142,   143,   144,   139,     0,   165,    67,    68,    69,
    70,   146,   147,   107,   140,   141,   142,   143,   144,   139,
    47,    48,    49,    50,    75,   166,   146,   147,     0,   140,
   141,   142,   143,   144,     0,     0,   172,     0,     0,     0,
     0,   146,   147,    -4,     1,     0,     2,     3,     4,     5,
     6,     7,     0,     0,     0,     8,    16,    42,     0,    18,
     0,     0,     0,     9,    24,   -65,   -65,   -65,   -65,     0,
   -74,   -74,   -74,   -74
};

static const short yycheck[] = {     0,
    36,    36,    38,    57,     6,     7,     8,     8,     6,    10,
     3,     4,     5,    31,    15,    16,    28,    18,   163,     6,
    16,     6,    34,    24,     6,     7,     8,    81,     0,    41,
   175,    27,    34,     6,    32,    36,    28,    30,    10,    31,
    34,    37,    96,    15,    40,    37,    82,    29,    44,    30,
    31,    47,    48,    49,    50,    13,     7,     8,   112,    27,
    96,    96,     6,     7,     8,    23,    24,    25,    26,    27,
    34,    67,    68,    69,    70,     6,    44,    35,    36,    47,
    48,    49,    50,    28,    29,    29,    31,    33,    84,    85,
    86,    34,    88,    32,   148,    96,     6,    30,    34,    67,
    68,    69,    70,   124,    37,    38,    39,    40,    42,   130,
   164,    28,    29,   167,   110,    30,    31,    34,   139,   140,
   141,   142,   176,    31,    41,   146,   147,    30,    34,   150,
   151,   167,   167,    29,    37,    38,    39,    40,    30,    31,
   176,   176,     6,     7,     8,   166,     1,    29,     3,     4,
     5,     6,     7,     8,     9,    10,    11,     6,     7,     8,
    15,    30,    17,    29,    29,    20,   167,    22,    37,    38,
    39,    40,    34,    85,    86,   176,    88,    32,    33,    34,
     1,    34,     3,     4,     5,     6,     7,     8,     9,    10,
    11,     3,     4,     5,    15,    14,    17,    30,     9,    20,
     1,    22,     3,     4,     5,     6,     7,     8,     9,    10,
    11,    32,    33,    34,    15,    29,    17,    32,    34,    20,
    19,    22,    32,     1,    13,     3,     4,     5,     6,     7,
     8,    32,    33,    34,    23,    24,    25,    26,    27,    13,
    34,    30,    20,    33,     0,    33,    35,    36,     0,    23,
    24,    25,    26,    27,    13,    82,    30,    37,    38,    39,
    40,    35,    36,    30,    23,    24,    25,    26,    27,    13,
    37,    38,    39,    40,    42,    34,    35,    36,    -1,    23,
    24,    25,    26,    27,    13,    -1,    30,    37,    38,    39,
    40,    35,    36,    30,    23,    24,    25,    26,    27,    13,
    37,    38,    39,    40,    52,    34,    35,    36,    -1,    23,
    24,    25,    26,    27,    -1,    -1,    30,    -1,    -1,    -1,
    -1,    35,    36,     0,     1,    -1,     3,     4,     5,     6,
     7,     8,    -1,    -1,    -1,    12,    28,    29,    -1,    31,
    -1,    -1,    -1,    20,    31,    37,    38,    39,    40,    -1,
    37,    38,    39,    40
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 5:
#line 44 "parser.y"
{
	if (yyvsp[-4].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline()); errc++;
	}

	if (!(strcmp(yyvsp[-3].str,"printf") && strcmp(yyvsp[-3].str,"scanf") && strcmp(yyvsp[-3].str,"getc") && strcmp(yyvsp[-3].str,"gets") && strcmp(yyvsp[-3].str,"getchar") && strcmp	(yyvsp[-3].str,"puts") && strcmp(yyvsp[-3].str,"putchar") && strcmp(yyvsp[-3].str,"clearerr") && strcmp(yyvsp[-3].str,"getw") && strcmp(yyvsp[-3].str,"putw") && strcmp(yyvsp[-3].str,"putc") && strcmp(yyvsp[-3].str,"rewind") && strcmp(yyvsp[-3].str,"sprint") && strcmp(yyvsp[-3].str,"sscanf") && strcmp(yyvsp[-3].str,"remove") && strcmp(yyvsp[-3].str,"fflush")))
		{printf("Error : Redeclaration of %s : Line %d\n",yyvsp[-3].str,printline()); errc++;}
	else
	{
		insert(yyvsp[-3].str,FUNCTION);
		insert(yyvsp[-3].str,yyvsp[-4].ival);
	}
	;
    break;}
case 6:
#line 58 "parser.y"
{
	if (yyvsp[-5].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline()); errc++;
	}

	if (!(strcmp(yyvsp[-4].str,"printf") && strcmp(yyvsp[-4].str,"scanf") && strcmp(yyvsp[-4].str,"getc") && strcmp(yyvsp[-4].str,"gets") && strcmp(yyvsp[-4].str,"getchar") && strcmp	(yyvsp[-4].str,"puts") && strcmp(yyvsp[-4].str,"putchar") && strcmp(yyvsp[-4].str,"clearerr") && strcmp(yyvsp[-4].str,"getw") && strcmp(yyvsp[-4].str,"putw") && strcmp(yyvsp[-4].str,"putc") && strcmp(yyvsp[-4].str,"rewind") && strcmp(yyvsp[-4].str,"sprint") && strcmp(yyvsp[-4].str,"sscanf") && strcmp(yyvsp[-4].str,"remove") && strcmp(yyvsp[-4].str,"fflush")))
		{printf("Error : Redeclaration of %s : Line %d\n",yyvsp[-4].str,printline());errc++;}
	else
	{
		insert(yyvsp[-4].str,FUNCTION);
		insert(yyvsp[-4].str,yyvsp[-5].ival);
                for(j=0;j<=k;j++)
                {insertp(yyvsp[-4].str,plist[j]);}
                k=-1;
	}
	;
    break;}
case 9:
#line 81 "parser.y"
{plist[++k]=yyvsp[-1].ival;insert(yyvsp[0].str,yyvsp[-1].ival);insertscope(yyvsp[0].str,i);;
    break;}
case 22:
#line 102 "parser.y"
{

					if(!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str)))
						storereturn(ct,FLOAT);
					else
						storereturn(ct,INT);
					ct++;
				;
    break;}
case 23:
#line 110 "parser.y"
{storereturn(ct,VOID); ct++;;
    break;}
case 24:
#line 111 "parser.y"
{
                          int sct=returnscope(yyvsp[-1].str,stack[top-1]);	//stack[top-1] - current scope
		          int type=returntype(yyvsp[-1].str,sct);
                          if (type==259) storereturn(ct,FLOAT);
                          else storereturn(ct,INT);
                          ct++;
                         ;
    break;}
case 31:
#line 130 "parser.y"
{loop=1;;
    break;}
case 32:
#line 130 "parser.y"
{loop=0;;
    break;}
case 34:
#line 133 "parser.y"
{loop=1;;
    break;}
case 35:
#line 133 "parser.y"
{loop=0;;
    break;}
case 52:
#line 156 "parser.y"
{
		int sct=returnscope(yyvsp[-2].str,stack[top-1]);
		int type=returntype(yyvsp[-2].str,sct);
		if((!(strspn(yyvsp[0].str,"0123456789")==strlen(yyvsp[0].str))) && type==258)
			{printf("\nError : Type Mismatch : Line %d\n",printline()); errc++;}
                else if (type==273)  {printf("\nError : Type Mismatch : Line %d\n",printline());errc++;}
		if(!lookup(yyvsp[-2].str))
		{
			int currscope=stack[top-1];
			int scope=returnscope(yyvsp[-2].str,currscope);
			if((scope<=currscope && end[scope]==0) && !(scope==0))
				check_scope_update(yyvsp[-2].str,yyvsp[0].str,currscope);
		}
	;
    break;}
case 53:
#line 172 "parser.y"
{
		if(lookup(yyvsp[-2].str))
			printf("\nUndeclared Variable %s : Line %d\n",yyvsp[-2].str,printline()); errc++;
	;
    break;}
case 56:
#line 179 "parser.y"
{
		if(lookup(yyvsp[0].str))
			{ printf("\nUndeclared Variable %s : Line %d\n",yyvsp[0].str,printline()); errc++; }
	;
    break;}
case 57:
#line 184 "parser.y"
{
                int sct=returnscope(yyvsp[-5].str,stack[top-1]);
		int type=returntype(yyvsp[-5].str,sct);
                //printf("%s",$3);
                int rtype;
                rtype=returntypef(yyvsp[-3].str); int ch=0;
                //printf("%d",rtype);
		if(rtype!=type)
			{ printf("\nError : Type Mismatch : Line %d\n",printline()); errc++;}
		if(!lookup(yyvsp[-5].str))
		{
		  for(j=0;j<=l;j++)
                  {ch = ch+checkp(yyvsp[-3].str,flist[j],j);}
                  if(ch>0) { printf("\nError : Parameter Type Mistake or Function undeclared : Line %d\n",printline()); errc++;}
                  l=-1;
		}
	;
    break;}
case 58:
#line 202 "parser.y"
{
                int sct=returnscope(yyvsp[-3].str,stack[top-1]);
		int type=returntype(yyvsp[-3].str,sct); int ch=0;
		if(!lookup(yyvsp[-3].str))
		{
		  for(j=0;j<=l;j++)
                  {ch = ch+checkp(yyvsp[-3].str,flist[j],j);}
                  if(ch>0) { printf("\nError : Parameter Type Mistake or Required Function undeclared : Line %d\n",printline()); errc++;}
                  l=-1;
		}
                else {printf("\nUndeclared Function %s : Line %d\n",yyvsp[-3].str,printline());errc++;}
	;
    break;}
case 62:
#line 233 "parser.y"
{
                if(lookup(yyvsp[0].str))
	        	{printf("\nUndeclared Variable %s : Line %d\n",yyvsp[0].str,printline());errc++;}
                else
                {
                	int sct=returnscope(yyvsp[0].str,stack[top-1]);
                	flist[++l]=returntype(yyvsp[0].str,sct);
                }
	;
    break;}
case 63:
#line 244 "parser.y"
{c=0;;
    break;}
case 65:
#line 249 "parser.y"
{
		if(c==0)							//check compatibility of mathematical operations
		{
			c=1;
			int sct=returnscope(yyvsp[0].str,stack[top-1]);
			b=returntype(yyvsp[0].str,sct);
		}
		else
		{
			int sct1=returnscope(yyvsp[0].str,stack[top-1]);
			if(b!=returntype(yyvsp[0].str,sct1)){}
				{printf("\nError : Type Mismatch : Line %d\n",printline());errc++;}
		}
	;
    break;}
case 77:
#line 279 "parser.y"
{
		if( (!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) && yyvsp[-4].ival==258)
			{printf("\nError : Type Mismatch : Line %d\n",printline());errc++;}
                else if (yyvsp[-4].ival==273)  {printf("\nError : Type Mismatch : Line %d\n",printline());errc++;}
		if(!lookup(yyvsp[-3].str))
		{
			int currscope=stack[top-1];
			int previous_scope=returnscope(yyvsp[-3].str,currscope);
			if(currscope==previous_scope)
				{printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-3].str,printline());errc++;}
			else
			{
				insert_dup(yyvsp[-3].str,yyvsp[-4].ival,currscope);
				check_scope_update(yyvsp[-3].str,yyvsp[-1].str,stack[top-1]);
			}
		}
		else
		{
			int scope=stack[top-1];
			insert(yyvsp[-3].str,yyvsp[-4].ival);
			insertscope(yyvsp[-3].str,scope);
			check_scope_update(yyvsp[-3].str,yyvsp[-1].str,stack[top-1]);
		}
	;
    break;}
case 78:
#line 304 "parser.y"
{
		if(!lookup(yyvsp[-1].str))
		{
			int currscope=stack[top-1];
			int scope=returnscope(yyvsp[-1].str,currscope);
			int type=returntype(yyvsp[-1].str,scope);
			if(!(scope<=currscope && end[scope]==0) || scope==0 && type!=271)
				{printf("\nError : Variable %s out of scope : Line %d\n",yyvsp[-1].str,printline());errc++;}
		}
		else
			{printf("\nError : Undeclared Variable %s : Line %d\n",yyvsp[-1].str,printline());errc++;}
	;
    break;}
case 79:
#line 317 "parser.y"
{
        	if(!lookup(yyvsp[-1].str))
		{
			int currscope=stack[top-1];
			int previous_scope=returnscope(yyvsp[-1].str,currscope);
			if(currscope==previous_scope)
				{printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-1].str,printline());errc++;}
			else
			{
				insert_dup(yyvsp[-1].str,yyvsp[-2].ival,currscope);
				//check_scope_update($2,$4,stack[top-1]);
			}
		}
		else
		{
			int scope=stack[top-1];
			//printf("%d",type);
			insert(yyvsp[-1].str,yyvsp[-2].ival);
			insertscope(yyvsp[-1].str,scope);
			//check_scope_update($2,$4,stack[top-1]);
		}
	;
    break;}
case 80:
#line 339 "parser.y"
{
                       int itype;
                       if(!(strspn(yyvsp[-2].str,"0123456789")==strlen(yyvsp[-2].str))) { itype=259; } else itype = 258;
                       if(itype!=258)
                       { printf("\nError : Array index must be of type int : Line %d\n",printline());errc++;}
                       if(atoi(yyvsp[-2].str)<=0)
                       { printf("\nError : Array index must be of type int > 0 : Line %d\n",printline());errc++;}
                       if(!lookup(yyvsp[-4].str))
		       {
			int currscope=stack[top-1];
			int previous_scope=returnscope(yyvsp[-4].str,currscope);
			if(currscope==previous_scope)
				{printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-4].str,printline());errc++;}
			else
			{

				insert_dup(yyvsp[-4].str,ARRAY,currscope);
                                insert_by_scope(yyvsp[-4].str,yyvsp[-5].ival,currscope);	//to insert type to the correct identifier in case of multiple entries of the identifier by using scope
                                if (itype==258) {insert_index(yyvsp[-4].str,yyvsp[-2].str);}
			}
		      }
		      else
		      {
			int scope=stack[top-1];
                        insert(yyvsp[-4].str,ARRAY);
			insert(yyvsp[-4].str,yyvsp[-5].ival);
			insertscope(yyvsp[-4].str,scope);
                        if (itype==258) {insert_index(yyvsp[-4].str,yyvsp[-2].str);}
		      }

		    ;
    break;}
case 81:
#line 370 "parser.y"
{
						insert(yyvsp[-4].str,STRUCT);
						;
    break;}
case 82:
#line 373 "parser.y"
{
				insert(yyvsp[-1].str,STRUCT_VAR);
				;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 381 "parser.y"


#include "lex.yy.c"
#include<ctype.h>
int main(int argc, char *argv[])
{
	yyin =fopen(argv[1],"r");
	if(!yyparse()&& errc<=0)
	{
		printf("\nParsing Completed\n");
		display();
	}
	else
	{
		printf("\nParsing Failed\n");
                display();
	}
	fclose(yyin);
	return 0;
}

yyerror(char *s)
{
	printf("\nLine %d : %s %s\n",yylineno,s,yytext);
}

int printline()
{
	return yylineno;
}
void push()
{
	stack[top]=i;
	i++;
	top++;
	return;
}
void pop()
{
	top--;
	end[stack[top]]=1;
	stack[top]=0;
	return;
}
