#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

#include <stdio.h>
#include <stdlib.h>
#include "symbolTable.c"

int g_addr = 100;
int i=1,lnum1=0;
int stack[100],index1=0,end[100],arr[10],ct,c,b,fl,top=0,label[20],label_num=0,ltop=0;
char st1[100][10];
char temp_count[2]="0";
int plist[100],flist[100],k=-1,errc=0,j=0;
char temp[2]="t";
char null[2]=" ";
void yyerror(char *s);
int printline();
extern int yylineno;
void scope_start()
{
	stack[index1]=i;
	i++;
	index1++;
	return;
}
void scope_end()
{
	index1--;
	end[stack[index1]]=1;
	stack[index1]=0;
	return;
}
void if1()
{
	label_num++;
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = not %s\n",temp,st1[top]);
 	printf("if %s goto L%d\n",temp,label_num);
	temp_count[0]++;
	label[++ltop]=label_num;

}
void if2()
{
	label_num++;
	printf("\ngoto L%d\n",label_num);
	printf("L%d: \n",label[ltop--]);
	label[++ltop]=label_num;
}
void if3()
{
	printf("\nL%d:\n",label[ltop--]);
}
void while1()
{
	label_num++;
	label[++ltop]=label_num;
	printf("\nL%d:\n",label_num);
}
void while2()
{
	label_num++;
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = not %s\n",temp,st1[top--]);
 	printf("if %s goto L%d\n",temp,label_num);
	temp_count[0]++;
	label[++ltop]=label_num;
}
void while3()
{
	int y=label[ltop--];
	printf("\ngoto L%d\n",label[ltop--]);
	printf("L%d:\n",y);
}
void dowhile1()
{
	label_num++;
	label[++ltop]=label_num;
	printf("\nL%d:\n",label_num);
}
void dowhile2()
{
 	printf("\nif %s goto L%d\n",st1[top--],label[ltop--]);
}
void for1()
{
	label_num++;
	label[++ltop]=label_num;
	printf("\nL%d:\n",label_num);
}
void for2()
{
	label_num++;
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = not %s\n",temp,st1[top--]);
 	printf("if %s goto L%d\n",temp,label_num);
	temp_count[0]++;
	label[++ltop]=label_num;
	label_num++;
	printf("goto L%d\n",label_num);
	label[++ltop]=label_num;
	label_num++;
	printf("L%d:\n",label_num);
	label[++ltop]=label_num;
}
void for3()
{
	printf("\ngoto L%d\n",label[ltop-3]);
	printf("L%d:\n",label[ltop-1]);
}
void for4()
{
	printf("\ngoto L%d\n",label[ltop]);
	printf("L%d:\n",label[ltop-2]);
	ltop-=4;
}
void push(char *a)
{
	strcpy(st1[++top],a);
}
void array1()
{
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = %s\n",temp,st1[top]);
	strcpy(st1[top],temp);
	temp_count[0]++;
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("%s = %s [ %s ] \n",temp,st1[top-1],st1[top]);
	top--;
	strcpy(st1[top],temp);
	temp_count[0]++;
}
void codegen()
{
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = %s %s %s\n",temp,st1[top-2],st1[top-1],st1[top]);
	top-=2;
	strcpy(st1[top],temp);
	temp_count[0]++;
}
void codegen_umin()
{
	strcpy(temp,"t");
	strcat(temp,temp_count);
	printf("\n%s = -%s\n",temp,st1[top]);
	top--;
	strcpy(st1[top],temp);
	temp_count[0]++;
}
void codegen_assign()
{
	printf("\n%s = %s\n",st1[top-2],st1[top]);
	top-=2;
}

#line 171 "parser.y"
typedef union {
		int ival;
		char *str;
	} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	VOID	260
#define	ID	261
#define	NUM	262
#define	REAL	263
#define	WHILE	264
#define	IF	265
#define	RETURN	266
#define	PREPROC	267
#define	LE	268
#define	STRING	269
#define	PRINT	270
#define	FUNCTION	271
#define	DO	272
#define	ARRAY	273
#define	ELSE	274
#define	STRUCT	275
#define	STRUCT_VAR	276
#define	FOR	277
#define	GE	278
#define	EQ	279
#define	NE	280
#define	INC	281
#define	DEC	282
#define	AND	283
#define	OR	284
#define	NEQ	285
#define	UMINUS	286


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int VOID;
static const int ID;
static const int NUM;
static const int REAL;
static const int WHILE;
static const int IF;
static const int RETURN;
static const int PREPROC;
static const int LE;
static const int STRING;
static const int PRINT;
static const int FUNCTION;
static const int DO;
static const int ARRAY;
static const int ELSE;
static const int STRUCT;
static const int STRUCT_VAR;
static const int FOR;
static const int GE;
static const int EQ;
static const int NE;
static const int INC;
static const int DEC;
static const int AND;
static const int OR;
static const int NEQ;
static const int UMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,VOID=260
	,ID=261
	,NUM=262
	,REAL=263
	,WHILE=264
	,IF=265
	,RETURN=266
	,PREPROC=267
	,LE=268
	,STRING=269
	,PRINT=270
	,FUNCTION=271
	,DO=272
	,ARRAY=273
	,ELSE=274
	,STRUCT=275
	,STRUCT_VAR=276
	,FOR=277
	,GE=278
	,EQ=279
	,NE=280
	,INC=281
	,DEC=282
	,AND=283
	,OR=284
	,NEQ=285
	,UMINUS=286


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::FLOAT=259;
const int YY_parse_CLASS::VOID=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::NUM=262;
const int YY_parse_CLASS::REAL=263;
const int YY_parse_CLASS::WHILE=264;
const int YY_parse_CLASS::IF=265;
const int YY_parse_CLASS::RETURN=266;
const int YY_parse_CLASS::PREPROC=267;
const int YY_parse_CLASS::LE=268;
const int YY_parse_CLASS::STRING=269;
const int YY_parse_CLASS::PRINT=270;
const int YY_parse_CLASS::FUNCTION=271;
const int YY_parse_CLASS::DO=272;
const int YY_parse_CLASS::ARRAY=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::STRUCT=275;
const int YY_parse_CLASS::STRUCT_VAR=276;
const int YY_parse_CLASS::FOR=277;
const int YY_parse_CLASS::GE=278;
const int YY_parse_CLASS::EQ=279;
const int YY_parse_CLASS::NE=280;
const int YY_parse_CLASS::INC=281;
const int YY_parse_CLASS::DEC=282;
const int YY_parse_CLASS::AND=283;
const int YY_parse_CLASS::OR=284;
const int YY_parse_CLASS::NEQ=285;
const int YY_parse_CLASS::UMINUS=286;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		204
#define	YYFLAG		-32768
#define	YYNTBASE	47

#define YYTRANSLATE(x) ((unsigned)(x) <= 286 ? yytranslate[x] : 107)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    39,
    40,    37,    35,    41,    36,     2,    38,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    44,    31,
    33,    32,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    45,     2,    46,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    42,     2,    43,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    34
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    10,    16,    23,    27,    29,    32,
    34,    36,    38,    42,    45,    46,    48,    50,    55,    57,
    59,    61,    65,    68,    72,    74,    80,    82,    83,    84,
    94,    95,    96,    97,   110,   111,   112,   121,   124,   125,
   126,   127,   135,   139,   143,   147,   151,   153,   155,   156,
   157,   158,   165,   169,   173,   175,   177,   179,   181,   182,
   183,   184,   193,   196,   203,   209,   216,   221,   223,   224,
   230,   231,   236,   237,   242,   244,   245,   246,   252,   253,
   254,   260,   261,   262,   268,   269,   270,   276,   277,   278,
   284,   285,   286,   292,   293,   294,   300,   301,   302,   308,
   309,   310,   316,   318,   319,   324,   325,   330,   332,   336,
   337,   341,   343
};

static const short yyrhs[] = {    48,
    47,     0,    12,    47,     0,    75,    47,     0,     0,    51,
     6,    39,    40,    52,     0,    51,     6,    39,    49,    40,
    52,     0,    49,    41,    50,     0,    50,     0,    51,     6,
     0,     3,     0,     4,     0,     5,     0,    42,    53,    43,
     0,    53,    54,     0,     0,    75,     0,    62,     0,     6,
    39,    40,    44,     0,    66,     0,    55,     0,    58,     0,
    11,    74,    44,     0,    11,    44,     0,    11,     6,    44,
     0,    44,     0,    15,    39,    14,    40,    44,     0,    52,
     0,     0,     0,    17,    56,    52,     9,    39,    81,    40,
    57,    44,     0,     0,     0,     0,    22,    39,    81,    59,
    44,    81,    60,    44,    81,    61,    40,    52,     0,     0,
     0,    10,    39,    81,    40,    63,    52,    64,    65,     0,
    19,    52,     0,     0,     0,     0,     9,    67,    39,    81,
    40,    68,    52,     0,     6,    33,    74,     0,     6,    35,
    69,     0,     6,    41,    69,     0,    74,    41,    69,     0,
     6,     0,    74,     0,     0,     0,     0,     6,    71,    33,
    72,    81,    73,     0,     6,    41,    70,     0,    74,    41,
    70,     0,     6,     0,    74,     0,     7,     0,     8,     0,
     0,     0,     0,    51,     6,    76,    33,    77,    81,    78,
    44,     0,    70,    44,     0,    51,     6,    45,    69,    46,
    44,     0,     6,    45,    70,    46,    44,     0,    20,     6,
    42,    75,    43,    44,     0,    20,     6,     6,    44,     0,
     1,     0,     0,     6,    80,    45,    81,    46,     0,     0,
    81,    35,    82,   102,     0,     0,    81,    36,    83,   102,
     0,   102,     0,     0,     0,     6,    84,    13,    85,    81,
     0,     0,     0,     6,    86,    23,    87,    81,     0,     0,
     0,     6,    88,    24,    89,    81,     0,     0,     0,     6,
    90,    30,    91,    81,     0,     0,     0,     6,    92,    28,
    93,    81,     0,     0,     0,     6,    94,    29,    95,    81,
     0,     0,     0,     6,    96,    31,    97,    81,     0,     0,
     0,     6,    98,    32,    99,    81,     0,     0,     0,     6,
   100,    33,   101,    81,     0,    79,     0,     0,   102,    37,
   103,   105,     0,     0,   102,    38,   104,   105,     0,   105,
     0,    39,    81,    40,     0,     0,    36,   106,   105,     0,
     6,     0,    74,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   177,   178,   179,   180,   183,   202,   221,   222,   225,   228,
   229,   230,   233,   236,   237,   240,   241,   242,   243,   244,
   245,   246,   252,   253,   260,   261,   262,   265,   265,   266,
   268,   268,   268,   268,   271,   271,   272,   274,   275,   278,
   278,   278,   281,   282,   283,   284,   285,   286,   289,   289,
   289,   290,   306,   310,   311,   315,   318,   319,   322,   322,
   322,   323,   353,   365,   395,   396,   400,   404,   407,   407,
   410,   410,   411,   411,   412,   413,   413,   413,   414,   414,
   414,   415,   415,   415,   416,   416,   416,   417,   417,   417,
   418,   418,   418,   419,   419,   419,   420,   420,   420,   421,
   421,   421,   422,   424,   424,   425,   425,   426,   428,   429,
   429,   430,   431
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"VOID","ID","NUM","REAL","WHILE","IF","RETURN","PREPROC","LE","STRING","PRINT",
"FUNCTION","DO","ARRAY","ELSE","STRUCT","STRUCT_VAR","FOR","GE","EQ","NE","INC",
"DEC","AND","OR","NEQ","'<'","'>'","'='","UMINUS","'+'","'-'","'*'","'/'","'('",
"')'","','","'{'","'}'","';'","'['","']'","start","Function","parameter_list",
"parameter","Type","CompoundStmt","StmtList","stmt","dowhile","@1","@2","for",
"@3","@4","@5","if","@6","@7","else","while","@8","@9","assignment","assignment1",
"@10","@11","@12","consttype","Declaration","@13","@14","@15","array","@16",
"E","@17","@18","@19","@20","@21","@22","@23","@24","@25","@26","@27","@28",
"@29","@30","@31","@32","@33","@34","@35","@36","T","@37","@38","F","@39",""
};
#endif

static const short yyr1[] = {     0,
    47,    47,    47,    47,    48,    48,    49,    49,    50,    51,
    51,    51,    52,    53,    53,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    56,    57,    55,
    59,    60,    61,    58,    63,    64,    62,    65,    65,    67,
    68,    66,    69,    69,    69,    69,    69,    69,    71,    72,
    73,    70,    70,    70,    70,    70,    74,    74,    76,    77,
    78,    75,    75,    75,    75,    75,    75,    75,    80,    79,
    82,    81,    83,    81,    81,    84,    85,    81,    86,    87,
    81,    88,    89,    81,    90,    91,    81,    92,    93,    81,
    94,    95,    81,    96,    97,    81,    98,    99,    81,   100,
   101,    81,    81,   103,   102,   104,   102,   102,   105,   106,
   105,   105,   105
};

static const short yyr2[] = {     0,
     2,     2,     2,     0,     5,     6,     3,     1,     2,     1,
     1,     1,     3,     2,     0,     1,     1,     4,     1,     1,
     1,     3,     2,     3,     1,     5,     1,     0,     0,     9,
     0,     0,     0,    12,     0,     0,     8,     2,     0,     0,
     0,     7,     3,     3,     3,     3,     1,     1,     0,     0,
     0,     6,     3,     3,     1,     1,     1,     1,     0,     0,
     0,     8,     2,     6,     5,     6,     4,     1,     0,     5,
     0,     4,     0,     4,     1,     0,     0,     5,     0,     0,
     5,     0,     0,     5,     0,     0,     5,     0,     0,     5,
     0,     0,     5,     0,     0,     5,     0,     0,     5,     0,
     0,     5,     1,     0,     4,     0,     4,     1,     3,     0,
     3,     1,     1
};

static const short yydefact[] = {     0,
    68,    10,    11,    12,    49,    57,    58,     0,     0,     0,
     0,     0,    56,     0,     0,     0,     0,     2,     0,     1,
    59,    63,     0,     3,    55,    53,     0,    50,     0,     0,
     0,     0,     0,    54,     0,     0,    67,     0,     0,     0,
     0,     8,     0,    47,     0,    48,    60,    65,   112,   110,
     0,   113,   103,    51,    75,   108,    59,     0,    15,     5,
     0,     0,     9,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    71,    73,    52,   104,   106,    66,     0,     6,     7,
    43,    44,    45,    64,    46,    61,     0,    77,    80,    83,
    86,    89,    92,    95,    98,   101,   112,   111,   109,     0,
     0,     0,     0,    49,    40,     0,     0,     0,    28,     0,
    13,    25,    27,    14,    20,    21,    17,    19,    16,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    72,    74,   105,   107,     0,     0,     0,     0,    23,     0,
     0,     0,     0,    62,    70,    78,    81,    84,    87,    90,
    93,    96,    99,   102,     0,     0,     0,    24,    22,     0,
     0,    31,    18,     0,    35,     0,     0,     0,    41,     0,
    26,     0,     0,     0,    36,     0,    32,    42,    39,    29,
     0,     0,    37,     0,     0,    38,    30,    33,     0,     0,
    34,     0,     0,     0
};

static const short yydefgoto[] = {    18,
    10,    41,    42,    11,    60,    88,   124,   125,   152,   194,
   126,   178,   191,   199,   127,   180,   189,   193,   128,   146,
   184,    45,    12,    17,    36,    84,    52,    14,    33,    69,
   130,    53,    70,    54,   110,   111,    71,   132,    72,   133,
    73,   134,    74,   135,    75,   136,    76,   137,    77,   138,
    78,   139,    79,   140,    55,   112,   113,    56,    80
};

static const short yypact[] = {   167,
-32768,-32768,-32768,-32768,    35,-32768,-32768,   167,     2,   167,
    25,    -4,    14,   167,    62,    62,    61,-32768,    -1,-32768,
    -3,-32768,    62,-32768,    12,-32768,    58,-32768,    53,   187,
     9,   120,    84,-32768,    79,    18,-32768,   131,    99,   116,
    37,-32768,   154,    15,   115,   122,-32768,-32768,    77,-32768,
    18,-32768,-32768,     8,    54,-32768,   121,   125,-32768,-32768,
   116,   151,-32768,   112,   120,   120,   132,   120,    18,   133,
   152,   157,   153,   159,   155,   168,   150,   164,   149,    26,
    63,-32768,-32768,-32768,-32768,-32768,-32768,   142,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,     8,    18,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    26,
    26,    26,    26,    19,-32768,   160,     3,   161,-32768,   162,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   158,
    -8,    18,    18,    18,    18,    18,    18,    18,    18,    18,
    54,    54,-32768,-32768,   163,   165,    18,   166,-32768,   169,
   184,   116,    18,-32768,-32768,     8,     8,     8,     8,     8,
     8,     8,     8,     8,   170,    18,    76,-32768,-32768,   171,
   196,     8,-32768,    78,-32768,   172,   173,   174,-32768,   116,
-32768,    18,    18,   116,-32768,    94,     8,-32768,   189,-32768,
   175,   116,-32768,   176,    18,-32768,-32768,     8,   177,   116,
-32768,   206,   209,-32768
};

static const short yypgoto[] = {     6,
-32768,-32768,   178,   -27,   -59,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    70,    51,-32768,-32768,-32768,     7,   -29,-32768,-32768,
-32768,-32768,-32768,   -51,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    29,-32768,-32768,   -61,-32768
};


#define	YYLAST		240


static const short yytable[] = {    81,
    39,    89,    38,    43,    29,   202,    13,    19,   148,     6,
     7,     2,     3,     4,    13,    20,    13,    96,   108,    24,
    13,    13,    13,    49,     6,     7,    82,    83,   123,    13,
    21,   107,     6,     7,    43,    31,    13,   155,    46,    22,
    30,    32,    82,    83,   -49,   131,   149,    64,    40,    65,
   143,   144,    15,    50,    23,    66,    51,   145,   129,    15,
    38,    50,   -55,    16,    51,    26,    27,    25,     6,     7,
    91,    46,    46,    34,    46,    15,    61,    62,   -55,    16,
   156,   157,   158,   159,   160,   161,   162,   163,   164,   -76,
    85,    86,   171,    28,    13,   167,    37,    82,    83,   -79,
   -82,   172,   109,    35,   -88,   -91,   -85,   -94,   -97,  -100,
    82,    83,    82,    83,   174,   175,    47,   179,     6,     7,
   185,   -69,    48,   150,   188,    44,     6,     7,    82,    83,
   186,   187,   196,   190,    92,    93,    57,    95,   141,   142,
   201,    58,     1,   198,     2,     3,     4,   114,     6,     7,
   115,   116,   117,     2,     3,     4,   118,    59,   119,    63,
    67,     9,    68,   120,    98,    32,    -4,     1,    87,     2,
     3,     4,     5,     6,     7,    94,   100,    97,     8,    99,
   104,   106,   102,    59,   121,   122,     9,     1,   101,     2,
     3,     4,     5,     6,     7,   105,   103,   170,   147,   151,
   153,   154,   165,   166,   177,   203,     9,   192,   204,   168,
   176,   182,   169,   173,     0,   181,   200,   183,   195,   197,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    90
};

static const short yycheck[] = {    51,
    30,    61,    30,    31,     6,     0,     0,     6,     6,     7,
     8,     3,     4,     5,     8,    10,    10,    69,    80,    14,
    14,    15,    16,     6,     7,     8,    35,    36,    88,    23,
     6,     6,     7,     8,    62,    39,    30,    46,    32,    44,
    42,    45,    35,    36,    33,    97,    44,    33,    40,    35,
   112,   113,    41,    36,    41,    41,    39,    39,    88,    41,
    88,    36,    44,    45,    39,    15,    16,     6,     7,     8,
    64,    65,    66,    23,    68,    41,    40,    41,    44,    45,
   132,   133,   134,   135,   136,   137,   138,   139,   140,    13,
    37,    38,   152,    33,    88,   147,    44,    35,    36,    23,
    24,   153,    40,    46,    28,    29,    30,    31,    32,    33,
    35,    36,    35,    36,   166,    40,    33,    40,     7,     8,
   180,    45,    44,   117,   184,     6,     7,     8,    35,    36,
   182,   183,   192,    40,    65,    66,     6,    68,   110,   111,
   200,    43,     1,   195,     3,     4,     5,     6,     7,     8,
     9,    10,    11,     3,     4,     5,    15,    42,    17,     6,
    46,    20,    41,    22,    13,    45,     0,     1,    44,     3,
     4,     5,     6,     7,     8,    44,    24,    45,    12,    23,
    31,    33,    28,    42,    43,    44,    20,     1,    30,     3,
     4,     5,     6,     7,     8,    32,    29,    14,    39,    39,
    39,    44,    40,    39,     9,     0,    20,    19,     0,    44,
    40,    39,    44,    44,    -1,    44,    40,    44,    44,    44,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    62
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 5:
#line 183 "parser.y"
{
	if(strcmp(yyvsp[-3].str,"main")!=0)
	{
		printf("goto F%d\n",lnum1);
	}
	if (yyvsp[-4].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline());
	}

	if (!(strcmp(yyvsp[-3].str,"printf") && strcmp(yyvsp[-3].str,"scanf") && strcmp(yyvsp[-3].str,"getc") && strcmp(yyvsp[-3].str,"gets") && strcmp(yyvsp[-3].str,"getchar") && strcmp	(yyvsp[-3].str,"puts") && strcmp(yyvsp[-3].str,"putchar") && strcmp(yyvsp[-3].str,"clearerr") && strcmp(yyvsp[-3].str,"getw") && strcmp(yyvsp[-3].str,"putw") && strcmp(yyvsp[-3].str,"putc") && strcmp(yyvsp[-3].str,"rewind") && strcmp(yyvsp[-3].str,"sprint") && strcmp(yyvsp[-3].str,"sscanf") && strcmp(yyvsp[-3].str,"remove") && strcmp(yyvsp[-3].str,"fflush")))
		printf("Error : Type mismatch in redeclaration of %s : Line %d\n",yyvsp[-3].str,printline());
	else
	{
		insert(yyvsp[-3].str,FUNCTION);
		insert(yyvsp[-3].str,yyvsp[-4].ival);
		g_addr+=4;
	}
	;
    break;}
case 6:
#line 202 "parser.y"
{
	if (yyvsp[-5].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline()); errc++;
	}

	if (!(strcmp(yyvsp[-4].str,"printf") && strcmp(yyvsp[-4].str,"scanf") && strcmp(yyvsp[-4].str,"getc") && strcmp(yyvsp[-4].str,"gets") && strcmp(yyvsp[-4].str,"getchar") && strcmp	(yyvsp[-4].str,"puts") && strcmp(yyvsp[-4].str,"putchar") && strcmp(yyvsp[-4].str,"clearerr") && strcmp(yyvsp[-4].str,"getw") && strcmp(yyvsp[-4].str,"putw") && strcmp(yyvsp[-4].str,"putc") && strcmp(yyvsp[-4].str,"rewind") && strcmp(yyvsp[-4].str,"sprint") && strcmp(yyvsp[-4].str,"sscanf") && strcmp(yyvsp[-4].str,"remove") && strcmp(yyvsp[-4].str,"fflush")))
	{printf("Error : Redeclaration of %s : Line %d\n",yyvsp[-4].str,printline());errc++;}
	else
	{
		insert(yyvsp[-4].str,FUNCTION);
		insert(yyvsp[-4].str,yyvsp[-5].ival);
		for(j=0;j<=k;j++)
		{insertp(yyvsp[-4].str,plist[j]);}
					k=-1;
	}
	;
    break;}
case 9:
#line 225 "parser.y"
{plist[++k]=yyvsp[-1].ival;insert(yyvsp[0].str,yyvsp[-1].ival);insertscope(yyvsp[0].str,i);;
    break;}
case 22:
#line 246 "parser.y"
{
					if(!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str)))
						storereturn(ct,FLOAT);
					else
						storereturn(ct,INT); ct++;
					;
    break;}
case 23:
#line 252 "parser.y"
{storereturn(ct,VOID); ct++;;
    break;}
case 24:
#line 253 "parser.y"
{
          int sct=returnscope(yyvsp[-1].str,stack[top-1]);	//stack[top-1] - current scope
		      int type=returntype(yyvsp[-1].str,sct);
          if (type==259) storereturn(ct,FLOAT);
          else storereturn(ct,INT);
          ct++;
    ;
    break;}
case 28:
#line 265 "parser.y"
{dowhile1();;
    break;}
case 29:
#line 265 "parser.y"
{dowhile2();;
    break;}
case 31:
#line 268 "parser.y"
{for1();;
    break;}
case 32:
#line 268 "parser.y"
{for2();;
    break;}
case 33:
#line 268 "parser.y"
{for3();;
    break;}
case 34:
#line 268 "parser.y"
{for4();;
    break;}
case 35:
#line 271 "parser.y"
{if1();;
    break;}
case 36:
#line 271 "parser.y"
{if2();;
    break;}
case 38:
#line 274 "parser.y"
{if3();;
    break;}
case 40:
#line 278 "parser.y"
{while1();;
    break;}
case 41:
#line 278 "parser.y"
{while2();;
    break;}
case 42:
#line 278 "parser.y"
{while3();;
    break;}
case 49:
#line 289 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 50:
#line 289 "parser.y"
{strcpy(st1[++top],"=");;
    break;}
case 51:
#line 289 "parser.y"
{codegen_assign();;
    break;}
case 52:
#line 290 "parser.y"
{
		int sct=returnscope(yyvsp[-5].str,stack[index1-1]);
		int type=returntype(yyvsp[-5].str,sct);
		if((!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) && type==258 && fl==0)
			printf("\nError : Type Mismatch : Line %d\n",printline());
		if(!lookup(yyvsp[-5].str))
		{
			int currscope=stack[index1-1];
			int scope=returnscope(yyvsp[-5].str,currscope);
			if((scope<=currscope && end[scope]==0) && !(scope==0))
			{
				check_scope_update(yyvsp[-5].str,yyvsp[-1].str,currscope);
			}
		}
		;
    break;}
case 53:
#line 306 "parser.y"
{
					if(lookup(yyvsp[-2].str))
						printf("\nUndeclared Variable %s : Line %d\n",yyvsp[-2].str,printline());
				;
    break;}
case 55:
#line 311 "parser.y"
{
		if(lookup(yyvsp[0].str))
			printf("\nUndeclared Variable %s : Line %d\n",yyvsp[0].str,printline());
		;
    break;}
case 59:
#line 322 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 60:
#line 322 "parser.y"
{strcpy(st1[++top],"=");;
    break;}
case 61:
#line 322 "parser.y"
{codegen_assign();;
    break;}
case 62:
#line 323 "parser.y"
{
		if( (!(strspn(yyvsp[-2].str,"0123456789")==strlen(yyvsp[-2].str))) && yyvsp[-7].ival==258 && (fl==0))
		{
			printf("\nError : Type Mismatch : Line %d\n",printline());
			fl=1;
		}
		if(!lookup(yyvsp[-6].str))
		{
			int currscope=stack[index1-1];
			int previous_scope=returnscope(yyvsp[-6].str,currscope);
			if(currscope==previous_scope)
				printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-6].str,printline());
			else
			{
				insert_dup(yyvsp[-6].str,yyvsp[-7].ival,currscope);
				check_scope_update(yyvsp[-6].str,yyvsp[-2].str,stack[index1-1]);
				int sg=returnscope(yyvsp[-6].str,stack[index1-1]);
				g_addr+=4;
			}
		}
		else
		{
			int scope=stack[index1-1];
			insert(yyvsp[-6].str,yyvsp[-7].ival);
			insertscope(yyvsp[-6].str,scope);
			check_scope_update(yyvsp[-6].str,yyvsp[-2].str,stack[index1-1]);
			g_addr+=4;
		}
	;
    break;}
case 63:
#line 353 "parser.y"
{
				if(!lookup(yyvsp[-1].str))
				{
					int currscope=stack[index1-1];
					int scope=returnscope(yyvsp[-1].str,currscope);
					if(!(scope<=currscope && end[scope]==0) || scope==0)
						printf("\nError : Variable %s out of scope : Line %d\n",yyvsp[-1].str,printline());
				}
				else
					printf("\nError : Undeclared Variable %s : Line %d\n",yyvsp[-1].str,printline());
				;
    break;}
case 64:
#line 365 "parser.y"
{
			int itype;
			if(!(strspn(yyvsp[-2].str,"0123456789")==strlen(yyvsp[-2].str))) { itype=259; } else itype = 258;
			if(itype!=258)
			{ printf("\nError : Array index must be of type int : Line %d\n",printline());errc++;}
			if(atoi(yyvsp[-2].str)<=0)
			{ printf("\nError : Array index must be of type int > 0 : Line %d\n",printline());errc++;}
			if(!lookup(yyvsp[-4].str))
			{
				int currscope=stack[top-1];
				int previous_scope=returnscope(yyvsp[-4].str,currscope);
				if(currscope==previous_scope)
				{printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-4].str,printline());errc++;}
				else
				{
					insert_dup(yyvsp[-4].str,ARRAY,currscope);
				insert_by_scope(yyvsp[-4].str,yyvsp[-5].ival,currscope);	//to insert type to the correct identifier in case of multiple entries of the identifier by using scope
					if (itype==258) {insert_index(yyvsp[-4].str,yyvsp[-2].str);}
				}
			}
			else
			{
				int scope=stack[top-1];
				insert(yyvsp[-4].str,ARRAY);
				insert(yyvsp[-4].str,yyvsp[-5].ival);
				insertscope(yyvsp[-4].str,scope);
				if (itype==258) {insert_index(yyvsp[-4].str,yyvsp[-2].str);}
			}
		;
    break;}
case 66:
#line 396 "parser.y"
{
						insert(yyvsp[-4].str,STRUCT);
						g_addr+=4;
						;
    break;}
case 67:
#line 400 "parser.y"
{
				insert(yyvsp[-1].str,STRUCT_VAR);
				g_addr+=4;
				;
    break;}
case 69:
#line 407 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 71:
#line 410 "parser.y"
{strcpy(st1[++top],"+");;
    break;}
case 72:
#line 410 "parser.y"
{codegen();;
    break;}
case 73:
#line 411 "parser.y"
{strcpy(st1[++top],"-");;
    break;}
case 74:
#line 411 "parser.y"
{codegen();;
    break;}
case 76:
#line 413 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 77:
#line 413 "parser.y"
{strcpy(st1[++top],"<=");;
    break;}
case 78:
#line 413 "parser.y"
{codegen();;
    break;}
case 79:
#line 414 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 80:
#line 414 "parser.y"
{strcpy(st1[++top],">=");;
    break;}
case 81:
#line 414 "parser.y"
{codegen();;
    break;}
case 82:
#line 415 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 83:
#line 415 "parser.y"
{strcpy(st1[++top],"==");;
    break;}
case 84:
#line 415 "parser.y"
{codegen();;
    break;}
case 85:
#line 416 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 86:
#line 416 "parser.y"
{strcpy(st1[++top],"!=");;
    break;}
case 87:
#line 416 "parser.y"
{codegen();;
    break;}
case 88:
#line 417 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 89:
#line 417 "parser.y"
{strcpy(st1[++top],"&&");;
    break;}
case 90:
#line 417 "parser.y"
{codegen();;
    break;}
case 91:
#line 418 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 92:
#line 418 "parser.y"
{strcpy(st1[++top],"||");;
    break;}
case 93:
#line 418 "parser.y"
{codegen();;
    break;}
case 94:
#line 419 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 95:
#line 419 "parser.y"
{strcpy(st1[++top],"<");;
    break;}
case 96:
#line 419 "parser.y"
{codegen();;
    break;}
case 97:
#line 420 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 98:
#line 420 "parser.y"
{strcpy(st1[++top],">");;
    break;}
case 99:
#line 420 "parser.y"
{codegen();;
    break;}
case 100:
#line 421 "parser.y"
{push(yyvsp[0].str);;
    break;}
case 101:
#line 421 "parser.y"
{strcpy(st1[++top],"=");;
    break;}
case 102:
#line 421 "parser.y"
{codegen_assign();;
    break;}
case 103:
#line 422 "parser.y"
{array1();;
    break;}
case 104:
#line 424 "parser.y"
{strcpy(st1[++top],"*");;
    break;}
case 105:
#line 424 "parser.y"
{codegen();;
    break;}
case 106:
#line 425 "parser.y"
{strcpy(st1[++top],"/");;
    break;}
case 107:
#line 425 "parser.y"
{codegen();;
    break;}
case 109:
#line 428 "parser.y"
{yyval.str=yyvsp[-1].str;;
    break;}
case 110:
#line 429 "parser.y"
{strcpy(st1[++top],"-");;
    break;}
case 111:
#line 429 "parser.y"
{codegen_umin();;
    break;}
case 112:
#line 430 "parser.y"
{push(yyvsp[0].str);fl=1;;
    break;}
case 113:
#line 431 "parser.y"
{push(yyvsp[0].str);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 434 "parser.y"


#include "lex.yy.c"
#include<ctype.h>


int main(int argc, char *argv[])
{
	yyin =fopen(argv[1],"r");
	yyparse();
	if(!yyparse())
	{
		printf("Parsing done\n");
		print();
	}
	else
	{
		printf("Error\n");
	}
	fclose(yyin);
	return 0;
}

void yyerror(char *s)
{
	printf("\nLine %d : %s %s\n",yylineno,s,yytext);
}
int printline()
{
	return yylineno;
}